const CART_KEY = "copaSmartStoreCart";
const getCart = () => JSON.parse(localStorage.getItem(CART_KEY)) || [];
const saveCart = (cart) => { localStorage.setItem(CART_KEY, JSON.stringify(cart)); updateCartCount(); };
function updateCartCount(){ const total = getCart().reduce((sum,item)=>sum+item.quantity,0); document.querySelectorAll('.cart-count').forEach(el=>el.textContent=total); }
function setupMenu(){ const btn=document.getElementById('menuToggle'); const links=document.getElementById('navLinks'); if(btn&&links){btn.addEventListener('click',()=>links.classList.toggle('show'));}}
function formatPrice(amount){ return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(amount); }
function addToCart(productId){ const product=products.find(p=>p.id===productId); if(!product) return; const cart=getCart(); const existing=cart.find(item=>item.id===productId); existing ? existing.quantity++ : cart.push({id:product.id,quantity:1}); saveCart(cart); alert(`${product.name} added to cart!`); }
function renderProducts(list=products){ const grid=document.getElementById('productGrid'); if(!grid) return; grid.innerHTML=list.length?list.map(p=>`<article class="product-card"><img src="${p.image}" alt="${p.name}"><h3>${p.name}</h3><p>${p.description}</p><div class="price">${formatPrice(p.price)}</div><button class="btn primary" onclick="addToCart(${p.id})">Add to Cart</button></article>`).join(''):'<p class="empty">No products found.</p>'; }
function setupProductFilters(){ const search=document.getElementById('searchInput'); const category=document.getElementById('categoryFilter'); if(!search||!category) return; const apply=()=>{ const term=search.value.toLowerCase().trim(); const cat=category.value; const filtered=products.filter(p=>(cat==='all'||p.category===cat)&&(p.name.toLowerCase().includes(term)||p.description.toLowerCase().includes(term))); renderProducts(filtered); }; search.addEventListener('input',apply); category.addEventListener('change',apply); }
function changeQuantity(id,delta){ const cart=getCart().map(item=>item.id===id?{...item,quantity:item.quantity+delta}:item).filter(item=>item.quantity>0); saveCart(cart); renderCart(); }
function removeFromCart(id){ saveCart(getCart().filter(item=>item.id!==id)); renderCart(); }
function renderCart(){ const container=document.getElementById('cartContainer'); if(!container) return; const cart=getCart(); if(!cart.length){container.innerHTML='<div class="empty"><h2>Your cart is empty</h2><p>Add products from the products page.</p><a class="btn primary" href="products.html">Go to Products</a></div>'; return;} const detailed=cart.map(item=>({...products.find(p=>p.id===item.id),quantity:item.quantity})); const subtotal=detailed.reduce((sum,item)=>sum+item.price*item.quantity,0); const gst=Math.round(subtotal*0.18); const grand=subtotal+gst; container.innerHTML=`<div>${detailed.map(item=>`<article class="cart-item"><img src="${item.image}" alt="${item.name}"><div><h3>${item.name}</h3><p>${formatPrice(item.price)} × ${item.quantity}</p><div class="quantity"><button onclick="changeQuantity(${item.id},-1)">−</button> <strong>${item.quantity}</strong> <button onclick="changeQuantity(${item.id},1)">+</button></div></div><button class="remove-btn" onclick="removeFromCart(${item.id})">Remove</button></article>`).join('')}</div><aside class="summary-card"><h2>Order Summary</h2><p>Subtotal: <strong>${formatPrice(subtotal)}</strong></p><p>GST 18%: <strong>${formatPrice(gst)}</strong></p><hr><p>Grand Total: <strong>${formatPrice(grand)}</strong></p><a class="btn primary" href="checkout.html">Proceed to Checkout</a></aside>`; }
function setupCheckout(){ const form=document.getElementById('checkoutForm'); const msg=document.getElementById('formMessage'); if(!form) return; form.addEventListener('submit',(e)=>{ e.preventDefault(); if(!form.checkValidity()){ msg.style.color='#dc2626'; msg.textContent='Please fill all fields correctly.'; form.reportValidity(); return;} if(!getCart().length){ msg.style.color='#dc2626'; msg.textContent='Cart is empty. Please add products first.'; return;} localStorage.removeItem(CART_KEY); updateCartCount(); form.reset(); msg.style.color='#16a34a'; msg.textContent='Order placed successfully!'; }); }
document.addEventListener('DOMContentLoaded',()=>{ setupMenu(); updateCartCount(); renderProducts(); setupProductFilters(); renderCart(); setupCheckout(); });
